server:
  port: 8081
spring:
  application:
    name: IGsystem
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/igsystem?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 141592
  redis:
    host: 192.168.244.130
    port: 6379
    password: 123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
logging:
  level:
    com.IGsystem: debug
    org.springframework: DEBUG
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
IG:
  db:
    host: localhost
    pw: 123
  path:
#    /home/avatar/
     /D:/Java-code/images/
flask:
  host:
    localhost

