export const API: string = 'http://medical123.natapp1.cc'

export const LOGIN_PATH: string = '/users/login'

export const REGISTER_PATH: string = '/users/register'

export const GETMYDATA: string = '/users/me'

export const UPDATEMYDATA : string = '/users/update'

export const CHANGEMYPASS : string = '/users/updatePassword'

export const GETQUESTIONS : string = '/questionnaire/questions'

export const RECORDANSWER : string = '/questionnaire/answer'

export const GETRESULT : string = '/questionnaire/result'

export const LOGOUT : string = '/users/logout'

